#!/bin/bash

script=$1
nx=$2
ny=$3
condapath = $4
condaenv = $5

eval "$(condapath shell.bash hook)"
conda activate $condaenv
echo "Using $SLURM_NTASKS cores"
echo `which conda`

OMP_NUM_THREADS=1 `which mpirun` -np $SLURM_NTASKS python $script \
  --nx=$nx --ny=$ny --steps=6 \
  --solver=petsc --output="results/$SLURM_JOB_PARTITION/${script}.tsv"
